---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector-01
  become: true
  roles:
    - vector-role

- name: Установка LightHouse на Ubuntu
  hosts: lighthouse
  become: yes
  roles:
    - lighthouse-role   
 
